### PR TITLE
fix(docker): fix dockerfile

### PR DESCRIPTION
**Pull request by denis-ev**
this should fix your dev docker image problem @codefriar 
can you please test, /data is now empty and should only have files when mounted.

Signed-off-by: Denis Evers <denis-ev@users.noreply.github.com>

### CODE REVIEW

**Comment by denis-ev** [comment]
@codefriar docker/motd is showing up on run, you just need to add what you wanted to add.

**Comment by denis-ev** [comment]
@codefriar could you please check this one?
Excluding the motd part you wanted, it's ready to go.

**Comment by codefriar** [comment]
We should create another issue about thinking through the MOTD contents

**Review by codefriar — APPROVED** [review]

**Pull request merged**
