### PR TITLE
feat(automation): automatically add owner of merged PR as a contributor

### PR DESCRIPTION
**Pull request by denis-ev**
@voryzen Well, I now did find a way to add someone with a merged PR to a Org Group.

Signed-off-by: Denis Evers <denis-ev@users.noreply.github.com>

### CODE REVIEW

**Comment by voryzen** [comment]
Seriously?

Wow, so simple.

**Review by voryzen — APPROVED** [review]

**Comment by voryzen** [comment]
what do you think, @codefriar  ?

**Comment by codefriar** [comment]
I like it!

**Review by codefriar — APPROVED** [review]
lgtm

**Pull request merged**
