### PR TITLE
fix: switch from mkdocs to docusaurus v2

### PR DESCRIPTION
**Pull request by denis-ev**

### CODE REVIEW

**Review by voryzen — APPROVED** [review]

**Review by voryzen — COMMENTED** [review]
This PR has code changes from other PRs..

**Comment by denis-ev** [comment]
> This PR has code changes from other PRs..

It's still WIP ... just ignore it until either you work on it or it's ready for review.

**Comment by voryzen** [comment]
Might be worthwhile keeping it as a branch.. Like the thor CLI

**Comment by denis-ev** [comment]
> Might be worthwhile keeping it as a branch.. Like the thor CLI

It is. This is just easier to not forget and get others involved because they can see that `help wanted`. 
Just don't approve stuff that's still WIP and not ready to be reviewed

**Comment by voryzen** [comment]
are you working on it?

**Comment by denis-ev** [comment]
Well, 
the new docs work and could be deployed.
In a new PR I'll add versioning and another one I'll update the pictures, so we have Github fork, etc. pictures and not the old ones.

To check it out `git checkout fix/switch-from-mkdocs-to-docusaurus-v2` then `cd website`, `yarn run build` and `yarn run serve`.

Merge when you're happy so far.

**Comment by denis-ev** [comment]
@codefriar @voryzen 
If anyone of you approves this, it will be automatically merged.
Check first and if you have anything, message me.

**Review by voryzen — APPROVED** [review]

**Pull request merged**
