### PR TITLE
feat: add pkg namespace

### PR DESCRIPTION
**Pull request by codefriar**
Re-added.

### CODE REVIEW

**Comment by denis-ev** [comment]
@codefriar 
```
bash-5.0# vlab --dev
[WARNING] Attempted to create command "vlab" without usage or description. Call desc if you want this method to be available as command or declare it inside a no_commands{} block. Invoked from "/usr/local/bundle/gems/thor-1.1.0/lib/thor.rb:239:in `define_method'".
(eval):2:in `help': super: no superclass method `help' for #<Vlab:0x00005633eed97ce0 @_invocations={Vlab=>["help"]}, @_initializer=[[], ["--dev"], {:shell=>#<Thor::Shell::Color:0x00005633eeda04a8 @base=#<Vlab:0x00005633eed97ce0 ...>, @mute=false, @padding=0, @always_force=false>, :current_command=>#<struct Thor::Command name="help", description="Describe subcommands or one specific subcommand", long_description=nil, usage="help [COMMAND]", options={}, ancestor_name="vlab">}], @options={"config_dir"=>"prod", "debug"=>:none, "dev"=>true, "disable_push"=>false}, @args=[], @shell=#<Thor::Shell::Color:0x00005633eeda04a8 @base=#<Vlab:0x00005633eed97ce0 ...>, @mute=false, @padding=0, @always_force=false>> (NoMethodError)
        from (eval):2:in `help'
        from /usr/local/bundle/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
        from /usr/local/bin/vlab:123:in `<main>'
```

**Comment by codefriar** [comment]
this reversion was an attempt at optimizing things. Please note than vlab line #37 and #42 are similar, but different. replacing #42 with a reference to 'rejected' results in the error you saw.

**Comment by denis-ev** [comment]
One more small thing ...
This one needs some spaces (10) or tabs (5) before the insert.

```
        "software/samba",
        "software/searx",
        "software/shinobi",
        "software/sickchill",
        "software/simply-shorten",
"software/snapdrop",
        "software/snibox",
        "software/sonarr",
        "software/speedtest",
        "software/statping",
        "software/sui",
```

**Comment by codefriar** [comment]
@denis-ev fixed that. it's a simple fix now, but if we don't anticipate the spacing changing much I'm ok with it

**Review by denis-ev — APPROVED** [review]

**Pull request merged**
