### PR TITLE
refactor(service): peertube fixes

### PR DESCRIPTION
**Pull request by voryzen**
Current issues with Peertube; fixed in this PR
1. not communicating with redis container
2. not 'properly' setting admin account (more specifically the password)
3. not communicating with the postfix container
4. live streaming now works; encrypted via traefik/letsencrypt

Updated:
1. docs

Caveats:
The 'default admin' password will be stored in plain text in the docker-compose file, and will be viewable upon docker inspect of the peertube container.. This is obviously not an issue if the server is properly secured, and/or if the user viewing the password is not malicious.

I have updated the docs to reflect these caveats; and to warn the user..

With some further thought it would be in the users best interest to note this in the docs;
1. that the default admin password should be considered a temporary password, and
2. to change this in the UI/CLI of the service, as soon as humanly possible to the true desired password

### CODE REVIEW

**Comment by voryzen** [comment]
the 'lookup' links/directories/locations, will need to be updated.

**Comment by codefriar** [comment]
@voryzen still wip?

**Comment by voryzen** [comment]
> @voryzen still wip?

Yep..
Working on getting the 'go live' streaming option to work.
Requires rtmp protocol and port 1935..

And if I can do it, i'd like to wrap it in a TLS/SSL session, which should be doable with traefik, bit I won't know until I portforward my servers port 1935

Obviously the user will need their infrastructure to have port 1935 open for to work..but at least the option is there

**Comment by voryzen** [comment]
The postfix issue has been rectified (turns out that it worked all along)
The user will need to make sure that their DNS is working OK.

I have noted everything required down in the docs. Peertube is ready for the world to use

**Review by codefriar — APPROVED** [review]

**Comment by codefriar** [comment]
@voryzen This PR is also failing due to pre-commit line whitespace ...

**Comment by denis-ev** [comment]
@voryzen that's why you should have pre-commit enabled by default or occasionally run 'pre-commit run --all'

**Comment by voryzen** [comment]
nah, no avail..
I've been getting this error, since after the separation
```
fknwhitspc]$ pre-commit run -all
Traceback (most recent call last):
  File "/home/voryzen/.local/bin/pre-commit", line 5, in <module>
    from pre_commit.main import main
ModuleNotFoundError: No module named 'pre_commit'
```
I'm not sure, I understand why there's an underscore, instead of a hyphon in that error

**Comment by voryzen** [comment]
the other option is that, either of you can close this PR, and add it yourself, if you really want.

After all pre-commit is not super necessary.. I tested this on my PC before I added the PR; and it's working like a charm

**Comment by codefriar** [comment]
@denis-ev  I'm going to override and fix.

@voryzen want to setup some time to figure out why pre-commit is throwing that error?

**Pull request merged**
