### PR TITLE
feat: auto run config new on docker image launch

### PR DESCRIPTION
**Pull request by codefriar**
## Pull Request template
Please, go through these steps before you submit a PR.

1. Make sure that your PR is not a duplicate.
2. If not, then make sure that:

    a. You have done your changes in a separate branch. Branches MUST have descriptive names that start with either the `fix/` or `feature/` prefixes. Good examples are: `fix/signin-issue` or `feature/issue-templates`.

    b. For Example `vlab update` doesn't throw any error. If it does, fix them first.

3. **After** these steps, you're ready to open a pull request.

    a. Your pull request MUST NOT target the `master` branch on this repository. You want to target `dev` instead.

    b. Give a descriptive title to your PR.

    c. Provide a description of your changes.

    d. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (always better if there is an issue for a Pull-Request).

IMPORTANT: Please review the [CONTRIBUTING.md](../CONTRIBUTING.md) file for detailed contributing guidelines.

**PLEASE REMOVE EVERYTHING ABOVE BEFORE SUBMITTING**

### CODE REVIEW

**Comment by denis-ev** [comment]
Could you add the fix for the ansi or path too? Or do you want another PR for that? 
@codefriar

**Comment by codefriar** [comment]
@denis-ev the ansi or path??

**Comment by denis-ev** [comment]
@codefriar ansible moving into the requirements, that fixiert your problem didn't it?

**Comment by codefriar** [comment]
that's actually in the PR I'm prepping for PenPot. Though I'm having trouble getting PenPot itself to work. may abandon pent and merging the rest of the work

**Review by denis-ev — APPROVED** [review]

**Pull request merged**
