### PR TITLE
refactor(ui): setup prompt changes

### PR DESCRIPTION
**Pull request by voryzen**
gives the user more information during setup..

I noticed a user had misunderstood what 'passwordless ssh keys' meant.
This is one step towards Vivum explaining itself to the user

### CODE REVIEW

**Review by codefriar — DISMISSED** [review]

**Comment by codefriar** [comment]
@voryzen this is failing the pre-commit check for end-of-line. Can you fix please? Since this is in your fork, it's not terribly easy for me to fix it

**Comment by voryzen** [comment]
> @voryzen this is failing the pre-commit check for end-of-line. Can you fix please? Since this is in your fork, it's not terribly easy for me to fix it

Are you referring to the playbook.config.yml?
I doesn't look like it has whitespace at the bottom..
It might be complaining about the copious amounts of white space within the yaml itself.. which are intentional.

here's a screenshot of the bottom of the file
Screenshot_20210126_133724

**Review by denis-ev — DISMISSED** [review]

**Comment by denis-ev** [comment]
@voryzen is pre-commit even installed on your computer? 
https://pre-commit.com/#install

Pre-commit should be installed in the docker container tho. You can run `pre-commit run --all` there, but you have to commit via your computers git because the container is not yet configured for that.

**Comment by voryzen** [comment]
> @voryzen is pre-commit even installed on your computer?
> https://pre-commit.com/#install
> 
> Pre-commit should be installed in the docker container tho. You can run `pre-commit run --all` there, but you have to commit via your computers git because the container is not yet configured for that.

yes, it's installed. However, as I said earlier, here is not whitespace down the bottom of the file.. the check says it does..
This doesn't seem like a user error, this appears to be an issue with the github action..

**Comment by denis-ev** [comment]
> > @voryzen is pre-commit even installed on your computer?
> > https://pre-commit.com/#install
> > Pre-commit should be installed in the docker container tho. You can run `pre-commit run --all` there, but you have to commit via your computers git because the container is not yet configured for that.
> 
> yes, it's installed. However, as I said earlier, here is not whitespace down the bottom of the file.. the check says it does..
> This doesn't seem like a user error, this appears to be an issue with the github action..

I just pulled your dev, this is my `pre-commit run --all` output:

```
➜  VivumLab git:(dev) pre-commit run --all
Check for missing I18n after puts or say.................................Passed
Trim Trailing Whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing playbook.config.yml

Fix End of Files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook

Fixing playbook.config.yml

Check that executables have shebangs.....................................Passed
Check for merge conflicts................................................Passed
Check Toml...........................................(no files to check)Skipped
Mixed line ending........................................................Passed
Don't commit to branch...................................................Failed
- hook id: no-commit-to-branch
- exit code: 1
yamllint.................................................................Passed
```

**Review by denis-ev — APPROVED** [review]

**Comment by voryzen** [comment]
> > > @voryzen is pre-commit even installed on your computer?
> > > https://pre-commit.com/#install
> > > Pre-commit should be installed in the docker container tho. You can run `pre-commit run --all` there, but you have to commit via your computers git because the container is not yet configured for that.
> > 
> > 
> > yes, it's installed. However, as I said earlier, here is not whitespace down the bottom of the file.. the check says it does..
> > This doesn't seem like a user error, this appears to be an issue with the github action..
> 
> I just pulled your dev, this is my `pre-commit run --all` output:
> 
> ```
> ➜  VivumLab git:(dev) pre-commit run --all
> Check for missing I18n after puts or say.................................Passed
> Trim Trailing Whitespace.................................................Failed
> - hook id: trailing-whitespace
> - exit code: 1
> - files were modified by this hook
> 
> Fixing playbook.config.yml
> 
> Fix End of Files.........................................................Failed
> - hook id: end-of-file-fixer
> - exit code: 1
> - files were modified by this hook
> 
> Fixing playbook.config.yml
> 
> Check that executables have shebangs.....................................Passed
> Check for merge conflicts................................................Passed
> Check Toml...........................................(no files to check)Skipped
> Mixed line ending........................................................Passed
> Don't commit to branch...................................................Failed
> - hook id: no-commit-to-branch
> - exit code: 1
> yamllint.................................................................Passed
> ```
and the screenshot above, shows that there is no whitespace at the bottom..
the files I have on my computer, have no whitespace down the bottom..

I'm not sure your intention.. but my part in this particular conversation is over

**Pull request merged**
