### PR TITLE
fix(service): fixing docs service

### PR DESCRIPTION
**Pull request by denis-ev**

### CODE REVIEW

**Comment by voryzen** [comment]
Can this be rebased?

**Comment by denis-ev** [comment]
rebased and force pushed

**Comment by voryzen** [comment]
is the new_service.md supposed to have a ticked option?

**Review by voryzen — APPROVED** [review]
Just make sure the option that has been ticked, in the new_service.md file is supposed to be there. Otherwise it looks goodd

**Review by denis-ev — COMMENTED** [review]
Should be fine now.

**Review by voryzen — APPROVED** [review]

**Pull request merged**
