### PR TITLE
feat(core): allows user to create/use different config files

### PR DESCRIPTION
**Pull request by voryzen**
allows user to create and to use different config files with the various vivumlab playbooks, using an extra user_config option.

vlab clone_config, sets a prefix, so the user can differentiate between the original and the user defined config files.

eg. answering vlab clone_config prompt, with... test1; will create test1-config.yml, test1-vault.yml, and test1-ansible_bash.vars.

Test and review, pleae

### CODE REVIEW

**Comment by voryzen** [comment]
Closes #124

**Comment by denis-ev** [comment]
I just tried the PR but I cannot get it to work.
```
vlab clone_config
What would you like to prefix the new files with? dev
cloning configs/Users/denis/git/VivumLab/tasks/UserActionTasks.sh: line 87: Task::decrypt user_config=: command not found
--- Stack trace from shell process 25673 depth=0 -------------
Failed command: "Task::decrypt user_config=$_user_config"
Return status: 127

File /Users/denis/git/VivumLab/tasks/UserActionTasks.sh, line 87, in Task::clone_config ()
File /usr/local/bin/vlab, line 721, in _taskit_run_task_with_args ()
File /usr/local/bin/vlab, line 653, in taskit_run ()
File /usr/local/bin/vlab, line 926, in taskit_main ()
File /usr/local/bin/vlab, line 938, in main ()
```

**Comment by voryzen** [comment]
That should be fixed.

I'm wondering if the case of a user wanting to make another copy of the already copied settings files, will be applicable.

More changes in code, but not impossible.

What is your opinion here @denis-ev ?

**Comment by denis-ev** [comment]
```
➜  VivumLab git:(clone_config_feature) vlab clone_config
What would you like to prefix the new files with? dev
cloning configs======== Decrypting Vault =======================================================================
/Users/denis/git/VivumLab/tasks/CoreTasks.sh: line 142: user_config: command not found
/Users/denis/git/VivumLab/tasks/helperFunctions.sh: line 178: user_config: command not found
/Users/denis/git/VivumLab/tasks/helperFunctions.sh: line 179: user_config: command not found
/Users/denis/git/VivumLab/tasks/helperFunctions.sh: line 178: user_config: command not found
/Users/denis/git/VivumLab/tasks/helperFunctions.sh: line 179: user_config: command not found
/Users/denis/git/VivumLab/tasks/helperFunctions.sh: line 178: user_config: command not found
/Users/denis/git/VivumLab/tasks/helperFunctions.sh: line 179: user_config: command not found
/Users/denis/git/VivumLab/tasks/helperFunctions.sh: line 178: user_config: command not found
/Users/denis/git/VivumLab/tasks/helperFunctions.sh: line 179: user_config: command not found
Unable to find image 'vivumlab/vivumlab:0.4.0' locally
0.4.0: Pulling from vivumlab/vivumlab
188c0c94c7c5: Already exists 
55578f60cda7: Already exists 
bcfc1cf21055: Already exists 
9a5a622b736a: Already exists 
359339bdbdba: Already exists 
ca4aac9fe343: Pull complete 
6563c6fc1f82: Pull complete 
Digest: sha256:a61bf7ebed8e93c5df6d3901e5debe3cb081fdbf6794cb4590235d4f04c8b347
Status: Downloaded newer image for vivumlab/vivumlab:0.4.0
Decryption successful
/Users/denis/git/VivumLab/tasks/CoreTasks.sh: line 143: user_config: command not found
--- Stack trace from shell process 27921 depth=1 -------------
Failed command: user_config
Return status: 127

File /Users/denis/git/VivumLab/tasks/CoreTasks.sh, line 143, in Task::decrypt ()
File /Users/denis/git/VivumLab/tasks/UserActionTasks.sh, line 87, in Task::clone_config ()
File /usr/local/bin/vlab, line 721, in _taskit_run_task_with_args ()
File /usr/local/bin/vlab, line 653, in taskit_run ()
File /usr/local/bin/vlab, line 926, in taskit_main ()
File /usr/local/bin/vlab, line 938, in main ()
/Users/denis/git/VivumLab/tasks/CoreTasks.sh: line 144: user_config: command not found
--- Stack trace from shell process 27927 depth=1 -------------
Failed command: user_config
Return status: 127

File /Users/denis/git/VivumLab/tasks/CoreTasks.sh, line 144, in Task::decrypt ()
File /Users/denis/git/VivumLab/tasks/UserActionTasks.sh, line 87, in Task::clone_config ()
File /usr/local/bin/vlab, line 721, in _taskit_run_task_with_args ()
File /usr/local/bin/vlab, line 653, in taskit_run ()
File /usr/local/bin/vlab, line 926, in taskit_main ()
File /usr/local/bin/vlab, line 938, in main ()
======== Vault decrypted! =======================================================================
======== Encrypting Vault =======================================================================
/Users/denis/git/VivumLab/tasks/CoreTasks.sh: line 128: user_config: command not found
/Users/denis/git/VivumLab/tasks/helperFunctions.sh: line 178: user_config: command not found
/Users/denis/git/VivumLab/tasks/helperFunctions.sh: line 179: user_config: command not found
/Users/denis/git/VivumLab/tasks/helperFunctions.sh: line 178: user_config: command not found
/Users/denis/git/VivumLab/tasks/helperFunctions.sh: line 179: user_config: command not found
/Users/denis/git/VivumLab/tasks/helperFunctions.sh: line 178: user_config: command not found
/Users/denis/git/VivumLab/tasks/helperFunctions.sh: line 179: user_config: command not found
/Users/denis/git/VivumLab/tasks/helperFunctions.sh: line 178: user_config: command not found
/Users/denis/git/VivumLab/tasks/helperFunctions.sh: line 179: user_config: command not found
Encryption successful
/Users/denis/git/VivumLab/tasks/CoreTasks.sh: line 129: user_config: command not found
--- Stack trace from shell process 28014 depth=1 -------------
Failed command: user_config
Return status: 127

File /Users/denis/git/VivumLab/tasks/CoreTasks.sh, line 129, in Task::encrypt ()
File /Users/denis/git/VivumLab/tasks/UserActionTasks.sh, line 91, in Task::clone_config ()
File /usr/local/bin/vlab, line 721, in _taskit_run_task_with_args ()
File /usr/local/bin/vlab, line 653, in taskit_run ()
File /usr/local/bin/vlab, line 926, in taskit_main ()
File /usr/local/bin/vlab, line 938, in main ()
/Users/denis/git/VivumLab/tasks/CoreTasks.sh: line 130: user_config: command not found
--- Stack trace from shell process 28020 depth=1 -------------
Failed command: user_config
Return status: 127

File /Users/denis/git/VivumLab/tasks/CoreTasks.sh, line 130, in Task::encrypt ()
File /Users/denis/git/VivumLab/tasks/UserActionTasks.sh, line 91, in Task::clone_config ()
File /usr/local/bin/vlab, line 721, in _taskit_run_task_with_args ()
File /usr/local/bin/vlab, line 653, in taskit_run ()
File /usr/local/bin/vlab, line 926, in taskit_main ()
File /usr/local/bin/vlab, line 938, in main ()
======== Vault encrypted! =======================================================================
/Users/denis/git/VivumLab/tasks/UserActionTasks.sh: line 92: Task::encrypt user_config=: command not found
--- Stack trace from shell process 26802 depth=0 -------------
Failed command: "Task::encrypt user_config=$_user_config"
Return status: 127

File /Users/denis/git/VivumLab/tasks/UserActionTasks.sh, line 92, in Task::clone_config ()
File /usr/local/bin/vlab, line 721, in _taskit_run_task_with_args ()
File /usr/local/bin/vlab, line 653, in taskit_run ()
File /usr/local/bin/vlab, line 926, in taskit_main ()
File /usr/local/bin/vlab, line 938, in main ()
```

I still get a lot of errors here.

**Comment by voryzen** [comment]
I can work on this, tomorrow morning.
I'm moving between this, and making the SSH stuff more robust; I think SSH tends to confuse a lot of people

**Comment by denis-ev** [comment]
You only need to test, I've fixed most of the problems already.

**Review by denis-ev — DISMISSED** [review]

**Review by denis-ev — DISMISSED** [review]

**Review by denis-ev — APPROVED** [review]

**Review by denis-ev — APPROVED** [review]

**Pull request merged**
