### PR TITLE
fix(service): update nextcloud 

### LINKED ISSUE #233: Bug: Nextcloud deployment broken
**Describe the bug**
Nextcloud permissions won't work.

**To Reproduce**
enable nextcloud
run `vlab update_one service=nextcloud`
-> service failing

**Expected behavior**
`vlab update_one service=nextcloud`
 -> service running

**Screenshots**

**Desktop (please complete the following information):**
 - Service: next cloud
 - Vivumlab Version: v0.5.2

**Additional context**

### PR DESCRIPTION
**Pull request by denis-ev**
Fixes Nextcloud deployment

- builds and not pulls image (nextcloud:fpm-alpine)
- custom build to fix custom uid/gid (copied from https://github.com/nextcloud/docker/pull/1278)
- changes from apache to fpm alpine nextcloud image
- adds nextcloud volume for use in web container

Closes #233

Signed-off-by: Denis Evers <denis-ev@users.noreply.github.com>

### CODE REVIEW

**Comment by codefriar** [comment]
I hate next cloud. I've never had anything but tears and regret getting it to run in this kind of context. I will test when I have my machine setup

**Comment by denis-ev** [comment]
Same bro, running nextcloud with docker has been a pain. But this worked quite well for me. 
And I hope for everyone else too.

**Comment by voryzen** [comment]
I'll test this tonight.

I've been reading through the code on my break.
I'm flummoxed as to why this hasn't been merged yet

**Review by codefriar — APPROVED** [review]
seems to work here. (very lightweight testing done)

**Pull request merged**
