### PR TITLE
fix: minify dockerfile by using alpine image

### PR DESCRIPTION
**Pull request by denis-ev**

### CODE REVIEW

**Comment by Kitsu01** [comment]
image
I ran ./launch.sh local and it doesn't seem like vlab is there after completing

**Comment by Kitsu01** [comment]
image
I ran ./launch.sh local and it doesn't seem like vlab is there after the build and run. Same for ./launch.sh local start

**Comment by Kitsu01** [comment]
My bad, I forgot the -v for -v local :).
At leas the CLI runs:

I have not tested deploying yet but I guess that it doesn't afffect
image

**Review by codefriar — APPROVED** [review]

**Pull request merged**
