### PR TITLE
fix: change https_only to hsts default true

### PR DESCRIPTION
**Pull request by denis-ev**
Signed-off-by: Denis Evers <denis-ev@users.noreply.github.com>

- [x] tested?

### CODE REVIEW

**Comment by denis-ev** [comment]
@voryzen @codefriar 
What do you guys think of the use of chains in Traefik, I think that makes it easier to read?

**Comment by codefriar** [comment]
@denis-ev  - WRT the chains, are you speaking about the way the traefik config has been updated?

**Comment by codefriar** [comment]
@denis-ev I accidentally pushed some cleanup work onto this branch. sorry.

**Comment by denis-ev** [comment]
ping @codefriar

**Review by codefriar — APPROVED** [review]

**Pull request merged**
