### PR TITLE
chore(changelog): cleanup

### PR DESCRIPTION
**Pull request by denis-ev**

### CODE REVIEW

**Review by voryzen — COMMENTED** [review]
Why are we removing entries from the changelog?

**Comment by denis-ev** [comment]
> Why are we removing entries from the changelog?

Have you seen what I removed? 
It's the unreleased part, which will never get removed, because those are PRs and Issues that are already fixed and should not be in there. They would be there forever.

**Comment by voryzen** [comment]
> > Why are we removing entries from the changelog?
> 
> Have you seen what I removed?
> It's the unreleased part, which will never get removed, because those are PRs and Issues that are already fixed and should not be in there. They would be there forever.

> > Why are we removing entries from the changelog?
> 
> Have you seen what I removed?
> It's the unreleased part, which will never get removed, because those are PRs and Issues that are already fixed and should not be in there. They would be there forever.

Yea, righto.

I don't know what it looked like beforehand, tbh.
Just merge. You know what you're doing

**Review by voryzen — DISMISSED** [review]

**Review by voryzen — APPROVED** [review]
Lets merge

**Pull request merged**
