### PR TITLE
feat: add save override files under settings and copy to server

### PR DESCRIPTION
**Pull request by denis-ev**
@codefriar Can we encrypt those files the same way we encrypt the config?
- [ ] encrypt docker-compose.override.yml files

### CODE REVIEW

**Comment by codefriar** [comment]
We could. Say more about why? We don't encrypt the passwords files... what're we accomplishing by encrypting them?

**Comment by denis-ev** [comment]
Well we should encrypt the password files too. 
I’m using an encrypted repo. But when everything is encrypted we could even go with a public, which could be easier and more secure for everyone.

**Comment by codefriar** [comment]
@denis-ev I had an idea but I'm not sure i'm terribly fond of it.

We could create an encrypted disk image to mount on settings. I'm afraid it's unnecessarily complex, and .. fragile

**Comment by denis-ev** [comment]
I would rather encrypt the folder or something.

**Comment by codefriar** [comment]
On the other hand, it'd be pretty straightforward to add a namespace to encrypted.yml for passwords. ie:

```yml
passwords:
  servicename:
    db: asldfk;asldkfj;asldkfj;as 
```

Still need to work out what to do with overrides

**Comment by denis-ev** [comment]
> On the other hand, it'd be pretty straightforward to add a namespace to encrypted.yml for passwords. ie:
> 
> ```yaml
> passwords:
>   servicename:
>     db: asldfk;asldkfj;asldkfj;as 
> ```
> 
> Still need to work out what to do with overrides

Yeah we could do that and we could create a loop for custom in the bottom
```
custom: 
  customkey: customvalue
```
So instead of filling the override file with the values we document how to use the variables?

**Comment by codefriar** [comment]
superseded by #285

**Pull request closed without merging**
