### PR TITLE
fix: improve authelia security / protected domains customizable

### PR DESCRIPTION
**Pull request by denis-ev**
Signed-off-by: Denis Evers <denis-ev@users.noreply.github.com>

### CODE REVIEW

**Review by codefriar — APPROVED** [review]
Awesome. Didn't know it could do that.

**Comment by denis-ev** [comment]
> Awesome. Didn't know it could do that.

Yeah Authelia is quite fun, you could even default Authelia protection and set the bypass within Authelia to not ask for password. 
At some point I want to add users with groups and then certain users can only access allowed services (depending on the group they are in)

**Comment by denis-ev** [comment]
@codefriar could you take a look, right now it can't run the ci config playbook, but I'm not sure why.

**Comment by denis-ev** [comment]
> @codefriar could you take a look, right now it can't run the ci config playbook, but I'm not sure why.

Problem is fixed now.

**Review by codefriar — APPROVED** [review]

**Pull request merged**
