### PR TITLE
refactor(docs): documentation update

### PR DESCRIPTION
**Pull request by voryzen**
massive documentation update.

refactored most of the documentation; there are parts that I haven't actually experienced with VivumLab (vagrant, bastion, etc), but I gave it a shot anyway.

Separated the radarr, and sonarr docs

added readarr to the index.md file (under ebooks)

fixed spelling mistakes

added a 'legal/acknowledgement/reference' md file

added a 'things to do' md file (Jobs to do/ where people can help)

### CODE REVIEW

**Comment by voryzen** [comment]
Should be ok now.

Just rechecked, found some discrepencies, and fixed them.

I'm going to sleep now

**Review by denis-ev — APPROVED** [review]

**Pull request merged**
