### PR TITLE
feat(config): adding multi config feat

### PR DESCRIPTION
**Pull request by denis-ev**

### CODE REVIEW

**Review by voryzen — DISMISSED** [review]
WIP, initiated

**Review by voryzen — APPROVED** [review]

**Comment by denis-ev** [comment]
There are conflicts, could you fix them? 
You have a better overview about the renaming you have done. @voryzen

**Comment by denis-ev** [comment]
@codefriar if you include the multi config function in your Thor cli feature, we can close this PR.

**Comment by codefriar** [comment]
@denis-ev i'm not sure what the multi-config feature is?

**Comment by denis-ev** [comment]
Discussion started in Zulip. Closing this for now.

**Pull request closed without merging**
