### PR TITLE
chore: :wastebasket: cleanup unnecessary files

### PR DESCRIPTION
**Pull request by denis-ev**

### CODE REVIEW

**Comment by voryzen** [comment]
I put all these into that folder, so that we had a reference.

Just in case we wanted to add those features in..

Migrations, one-liner (which might be more achievable in the short term, than a GUI)

**Comment by denis-ev** [comment]
@voryzen yes, but we can always go back in the history if we need to. 
Right now it's a folder that could confuse others. That's why I would like to get rid of it for now.

**Comment by voryzen** [comment]
@denis-ev yea, alright

**Review by voryzen — APPROVED** [review]
Lets keep the history alive

**Pull request merged**
