### PR TITLE
refactor(service): updating portainer

### LINKED ISSUE #240: Bug: Portainer image deprecated
**Describe the bug**
Portainer changed their docker image from portainer/portainer to portainer/portainer-ce

### PR DESCRIPTION
**Pull request by voryzen**
Portainer has changed their image naming conventions with their latest version (2.0.1), this update reflects that..

Closes #240

### CODE REVIEW

**Review by codefriar — COMMENTED** [review]
is portainer no longer doing a latest tag for portainer-ce?

**Review by denis-ev — DISMISSED** [review]

**Comment by voryzen** [comment]
> is portainer no longer doing a latest tag for portainer-ce?

they are.. but where possible, we don't use latest tags

**Comment by denis-ev** [comment]
> > is portainer no longer doing a latest tag for portainer-ce?
> 
> they are.. but where possible, we don't use latest tags

We try to not use them anymore and switching with verified badges over to static versions.
@codefriar

**Comment by voryzen** [comment]
> > > is portainer no longer doing a latest tag for portainer-ce?
> > 
> > 
> > they are.. but where possible, we don't use latest tags
> 
> We try to not use them anymore and switching with verified badges over to static versions.
> @codefriar

The obvious implication being that, if it is tested an working with a specific version, and the developer updates it (as is the issue with Pixelfed right now), and the version doesn't build, or play well with the other containers, or has bugs in the program itself, we have essentially verified and told the user that it works, when it doesn't..

This is a very old debate, from way back in the HLOS days

**Comment by denis-ev** [comment]
@voryzen Is this still WIP?

**Review by denis-ev — APPROVED** [review]

**Comment by voryzen** [comment]
It should be ok to merge,

would be worth testing, first

**Comment by denis-ev** [comment]
> It should be ok to merge,
> 
> would be worth testing, first

Tested with existing portainer, works.

**Pull request merged**
