### PR TITLE
fix(core): add new package wizard

### PR DESCRIPTION
**Pull request by voryzen**
change, and reconvene

Denis:
I added an experimental notice and that manual changes are required. 
With this merged we can add some more services and I can fix the small kinks in another PR.

### CODE REVIEW

**Comment by denis-ev** [comment]
Is it ready to be tested? @voryzen

**Comment by voryzen** [comment]
What is left to do on this?

**Comment by denis-ev** [comment]
@voryzen 
- the yq merge of the config destroys the config, not sure why yet.
- adding to mkdocs.yml still missing

**Comment by denis-ev** [comment]
Todo:
- [ ] config.yml gets destroyed with yq
- [ ] mkdocs.yml gets kinda destroyed too

**Comment by denis-ev** [comment]
Check it out. I've added an experimental notice, because it's not perfectly working yet.
I'll fix those problems in another PR, having this merged is a huge help for getting more services added.

**Review by denis-ev — APPROVED** [review]

**Comment by voryzen** [comment]
Lets do it. Merge, and we will see how it goes

**Pull request merged**
